export const REGISTER_EMPLOYEE: string = 'REGISTER_EMPLOYEE';

export const REGISTER_EMPLOYEE_FAIL: string = 'REGISTER_EMPLOYEE_FAIL';

export const REGISTER_EMPLOYEE_SUCCESS: string = 'REGISTER_EMPLOYEE_SUCCESS';